### ISSUE TITLE
Should `ngff.ImageArray` have a different name?

### ISSUE THREAD

**Issue by ziw-liu** [czbiohub/iohub#60]
From #45:

@mattersoflight suggested that we should rename `ngff.ImageArray`:

> Rename the ImageArray object to ZarrArray to make it obvious that the object is a zarr array.

In naming it as `ImageArray` I wanted to imply that this is *not only* a `zarr.Array` object and has additional methods/properties that are specific to our image data (e.g. `numpy()`, `channels`). Also we may have more backends added in the future (tensorstore) so that it may deviate more from the baseline zarr-python object.

Inviting more discussion on this topic so that we can agree on a nomenclature that offers more clarity.

**Comment by mattersoflight** [comment]
Since we have resolved at the D&D discussion that tensorstore is a viable backend, I agree `ZarrArray` is not the accurate name. Considering the discussion at #26  and D&D, it seems that `ngff` will need to use `zarr.heirarchy.group` and `tensorstore.TensorStore` to implement faster io.  

I am now partial towards `ngff.data` following napari's nomenclature of `layers.Image.data`, `layers.Labels.data`. In our case, the `data` object can be of a type `zarr.array` or `tensorstore.TensorStore`.

What is your vote @ziw-liu , @AhmetCanSolak , @JoOkuma , @talonchandler, @edyoshikun ? Please chime in soon so that Ziwen can refactor the API before first release.

**Comment by talonchandler** [comment]
Mimicking napari and using `ngff.data` makes sense to me. My impression of napari's `viewer.layers[0].data` command is that I can always expect to use `numpy`-like indexing on the result (even if the data is a zarr, a numpy array, etc). This is very intuitive IMO.

**Comment by edyoshikun** [comment]
I second @talonchandler that when calling `viewer.layers["layer_name"]`  or  `viewer.layers[0]`, I expect a numpy object as result. Using napari's nomenclature will consolidate the retrieval of both datatypes `zarr` or `tensorstore` intuitively.

**Comment by JoOkuma** [comment]
I'm still getting familiar with all the features of the library.
I took a glimpse at the `ImageArray` class, and it has a handful of very shallow methods.
It looks like it's mostly used for typing of the return type. Is that correct?

**Comment by JoOkuma** [comment]
I'm fine with `ngff.Data`, but I prefer `ngff.ImageArray`, data is a bit vague in my opinion.
NGFF might contain some non-image data in the future (e.g. spatial omics) and I think it won't inherit the same methods as `ngff.Data/ImageArray` class.

It should start with a capital letter as the majority of classes in Python.

**Comment by ziw-liu** [comment]
> I am now partial towards `ngff.data` following napari's nomenclature of `layers.Image.data`, `layers.Labels.data`. In our case, the `data` object can be of a type `zarr.array` or `tensorstore.TensorStore`.

One thing to notice is that for napari `data` is a named attribute (a property to be exact) of the `Image` class, and it is either an array object or a sequence of arrays (for multiscale data). Napari does not define the type of the array, and the name of the array class is defined in NumPy (`numpy.Array`). In this issue we are trying to determine the most clarifying name of the class. For discussion about the named attribute that gives an array-like object representing raw data in an NGFF node, see #61.

**Comment by mattersoflight** [comment]
👍🏼 Thanks for #61. `ImageArray` is a good name for this class with indexable `data` as its property. I suggest shortening the name further to `Image` (this class will deal with ND data), but there may be good reasons to stay with the current name. Feel free to decide and close this issue.

**Comment by ziw-liu** [comment]
I can see benefits in both `Image` and `ImageArray`. `Image` is shorter, but has potential name space conflicts with other image processing libraries such as PIL and napari. This is not a big issue since most users will not need to construct the NGFF image class themselves. But for the same reason having a slightly longer name wouldn't hurt experience too much.

> `ImageArray` is a good name for this class with indexable `data` as its property.

Just to clarify that `ImageArray` is already indexable (it's a child of `zarr.Array`), and `ImageArray.numpy()` returns the in-RAM NumPy array. The 'data' attribute I referred to is a property of `iohub.ngff.Position`.

I'm closing this for now and keep the current name. But feel free to reopen as things evolve.
